### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by bertuz** [dddinphp/blog-cqrs#3]
Hi all, I've tried to setup the project but when pointing to http://mydddblog.dev or http://www.mydddblog.dev I'm redirected to https and the connection is refused. How can I get around this? thanks

**Comment by bertuz** [comment]
Simple fix getaround: if you bump into this, just browse: http://172.21.99.6 and you're done.

**Comment by theUniC** [comment]
Hi,

This happens because the development environment uses a `.dev` domain. Since last year Google Chrome **[forces `dev` domains to go through a secure connection](https://medium.engineering/use-a-dev-domain-not-anymore-95219778e6fd)**.

It can be changed to use `.test` domain (changes are to be made on `resources/hosts`, `resources/httpd.conf` and `resources/provisioning.sh`) and it should work again as before. Feel free to send a PR.

Thanks!

**Comment by bertuz** [comment]
¡oído cocina! Ok PR done, thanks for the article :-)
